[package]
name = "battle_fox"
version = "0.1.0"
authors = ["Kiiya <snoewflaek@gmail.com>"]
edition = "2018"

[workspace]
members = ["battlefield_rcon"]

[dependencies]
# Cargo is smart enough to find a crate inside a bigger git repo.
# battlefield_rcon = { git = "https://github.com/Kiiyya/BattleFox", branch = "main" }
ascii = "1"
battlefield_rcon = { path = "battlefield_rcon" }
tokio = "1.2"
tokio-stream = "0.1"

dotenv = "0.15"
