[package]
name = "battle_fox"
version = "0.1.0"
authors = ["Kiiya <snoewflaek@gmail.com>"]
edition = "2018"

[workspace]
members = ["battlefield_rcon"]

[dependencies]
# battlefield_rcon = { git = "https://github.com/Kiiyya/battlefield_rcon", branch = "main" }
battlefield_rcon = { path = "battlefield_rcon" }
tokio = "1.2.0"
tokio-stream = "0.1.3"
