[profile.release]
lto = true
panic = 'abort'     # Abort on panic. Supposedly helps reduzing binary size.

[workspace]
members = [
	"battlefield_rcon",
	"battlefox",
	"battlefox_discord",
	"battlelog",
	"shared",
	"database",
]