enabled: true
n_options: 4
max_options: 6
max_noms_per_vip: 1
spammer_interval: 180
endscreen_votetime: 15
endscreen_post_votetime: 5
vip_ad: Get your VIP slot from example.com! Link in the server description.
vip_nom: VIPs can !nominate maps, get your VIP slot from Cool Community! Link in server description.
announce_nominator: false
animate: false
animate_override:
  Kiiyya: true
  xfileFIN: true
options_minlen: 2
options_reserved_hidden:
  - punish
options_reserved_trie:
  - p
  - f
  - v
