pop_states:
  - name: SeedingPopulation
    pool:
      pool:
        - map: Locker
          mode: Rush
        - map: PearlMarket
          mode: Rush
        - map: Propaganda
          mode: Rush
        - map: FloodZone
          mode: Rush
        - map: Metro
          mode: Rush
    min_players: 0
  - name: LowPopulation
    pool:
      pool:
        - map: Locker
          mode: Rush
        - map: Metro
          mode: Rush
        - map: PearlMarket
          mode: Rush
        - map: Propaganda
          mode: Rush
        - map: FloodZone
          mode: Rush
    min_players: 20
  - name: MediumPopulation
    pool:
      pool:
        - map: Locker
          mode: Rush
        - map: Metro
          mode: Rush
        - map: PearlMarket
          mode: Rush
        - map: Propaganda
          mode: Rush
        - map: FloodZone
          mode: Rush
        - map: Zavod
          mode: Rush
        - map: GolmudRailway
          mode: Rush
        - map: Shanghai
          mode: Rush
        - map: ParacelStorm
          mode: Rush
        - map: HainanResort
          mode: Rush
        - map: RogueTransmission
          mode: Rush
        - map: Dawnbreaker
          mode: Rush
    min_players: 40
  - name: HighPopulation
    pool:
      pool:
        - map: Zavod
          mode: Rush
        - map: LancangDam
          mode: Rush
        - map: FloodZone
          mode: Rush
        - map: GolmudRailway
          mode: Rush
        - map: ParacelStorm
          mode: Rush
        - map: Locker
          mode: Rush
        - map: HainanResort
          mode: Rush
        - map: Shanghai
          mode: Rush
        - map: RogueTransmission
          mode: Rush
        - map: Dawnbreaker
          mode: Rush
        - map: Metro
          mode: Rush
        - map: Oman
          mode: Rush
        - map: PearlMarket
          mode: Rush
        - map: Propaganda
          mode: Rush
        - map: Lumphini
          mode: Rush
        - map: SunkenDragon
          mode: Rush
    min_players: 50
vehicle_threshold: 30
leniency: 2
