n_options: 4
max_options: 6
max_noms_per_vip: 1
spammer_interval: 180
endscreen_votetime: 25
endscreen_post_votetime: 5
vip_ad: Get your VIP slot for 5$/month at bfcube.com!
vip_nom: 'VIPs can !nominate maps, get your VIP slot for 5$/month at bfcube.com!'
animate: false
animate_override:
  Kiiyya: true
  PocketWolfy: true
options_minlen: 1
options_reserved_hidden:
  - punish
options_reserved_trie:
  - p
  - f
  - v
