//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "adkats_users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub user_id: u32,
    pub user_name: String,
    pub user_email: Option<String>,
    pub user_phone: Option<String>,
    pub user_role: u32,
    pub user_expiration: DateTime,
    pub user_notes: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::adkats_roles::Entity",
        from = "Column::UserRole",
        to = "super::adkats_roles::Column::RoleId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AdkatsRoles,
    #[sea_orm(has_many = "super::adkats_usersoldiers::Entity")]
    AdkatsUsersoldiers,
}

impl Related<super::adkats_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdkatsRoles.def()
    }
}

impl Related<super::adkats_usersoldiers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdkatsUsersoldiers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
