//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "adkats_roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub role_id: u32,
    #[sea_orm(unique)]
    pub role_key: String,
    pub role_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::adkats_rolecommands::Entity")]
    AdkatsRolecommands,
    #[sea_orm(has_many = "super::adkats_rolegroups::Entity")]
    AdkatsRolegroups,
    #[sea_orm(has_many = "super::adkats_users::Entity")]
    AdkatsUsers,
}

impl Related<super::adkats_rolecommands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdkatsRolecommands.def()
    }
}

impl Related<super::adkats_rolegroups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdkatsRolegroups.def()
    }
}

impl Related<super::adkats_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdkatsUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
