//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "adkats_player_reputation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub player_id: u32,
    pub game_id: u8,
    pub target_rep: f32,
    pub source_rep: f32,
    pub total_rep: f32,
    pub total_rep_co: f32,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
