//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "adkats_settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub server_id: u16,
    #[sea_orm(primary_key, auto_increment = false)]
    pub setting_name: String,
    pub setting_type: String,
    pub setting_value: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_server::Entity",
        from = "Column::ServerId",
        to = "super::tbl_server::Column::ServerId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TblServer,
}

impl Related<super::tbl_server::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblServer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
