//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "battlemanager_roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::battlemanager_userroles::Entity")]
    BattlemanagerUserroles,
}

impl Related<super::battlemanager_userroles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BattlemanagerUserroles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
