//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "bfacp_settings_users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: u32,
    pub lang: String,
    pub timezone: String,
    pub notifications: i8,
    pub notifications_alert: i8,
    pub notifications_alert_sound: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bfacp_users::Entity",
        from = "Column::UserId",
        to = "super::bfacp_users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BfacpUsers,
}

impl Related<super::bfacp_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BfacpUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
