//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "bfacp_roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique)]
    pub name: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bfacp_assigned_roles::Entity")]
    BfacpAssignedRoles,
    #[sea_orm(has_many = "super::bfacp_permission_role::Entity")]
    BfacpPermissionRole,
}

impl Related<super::bfacp_assigned_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BfacpAssignedRoles.def()
    }
}

impl Related<super::bfacp_permission_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BfacpPermissionRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
