#![allow(clippy::derive_partial_eq_without_eq)]
//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub mod prelude;

pub mod adkats_bans;
pub mod adkats_battlecries;
pub mod adkats_battlelog_players;
pub mod adkats_challenge_definition;
pub mod adkats_challenge_definition_detail;
pub mod adkats_challenge_entry;
pub mod adkats_challenge_entry_detail;
pub mod adkats_challenge_reward;
pub mod adkats_challenge_rule;
pub mod adkats_commands;
pub mod adkats_infractions_global;
pub mod adkats_infractions_server;
pub mod adkats_orchestration;
pub mod adkats_player_reputation;
pub mod adkats_records_debug;
pub mod adkats_records_main;
pub mod adkats_rolecommands;
pub mod adkats_rolegroups;
pub mod adkats_roles;
pub mod adkats_settings;
pub mod adkats_specialplayers;
pub mod adkats_statistics;
pub mod adkats_users;
pub mod adkats_usersoldiers;
pub mod battlemanager_roles;
pub mod battlemanager_userroles;
pub mod battlemanager_users;
pub mod bfacp_assigned_roles;
// pub mod bfacp_migrations; // ! Has no primary key, so SeaORM can't deal with it
pub mod bfacp_options;
// pub mod bfacp_password_reminders; // ! Has no primary key, so SeaORM can't deal with it
pub mod bfacp_permission_role;
pub mod bfacp_permissions;
pub mod bfacp_roles;
// pub mod bfacp_sessions; // ! Has no primary key, so SeaORM can't deal with it
pub mod bfacp_settings_servers;
pub mod bfacp_settings_users;
pub mod bfacp_users;
pub mod bfacp_users_soldiers;
pub mod sea_orm_active_enums;
pub mod tbl_chatlog;
pub mod tbl_currentplayers;
pub mod tbl_dogtags;
pub mod tbl_extendedroundstats;
pub mod tbl_games;
pub mod tbl_mapstats;
pub mod tbl_playerdata;
pub mod tbl_playerrank;
pub mod tbl_playerstats;
pub mod tbl_server;
pub mod tbl_server_player;
pub mod tbl_server_stats;
pub mod tbl_sessions;
pub mod tbl_teamscores;
pub mod tbl_weapons;
pub mod tbl_weapons_stats;
pub mod vsm_tbrowsersessions;
pub mod vsm_tfilter;
pub mod vsm_tuser;
pub mod vsm_vips;
