//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ban_enforceIP")]
pub enum BanEnforceIp {
    #[sea_orm(string_value = "Y")]
    Y,
    #[sea_orm(string_value = "N")]
    N,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "command_logging")]
pub enum CommandLogging {
    #[sea_orm(string_value = "Log")]
    Log,
    #[sea_orm(string_value = "Mandatory")]
    Mandatory,
    #[sea_orm(string_value = "Ignore")]
    Ignore,
    #[sea_orm(string_value = "Unable")]
    Unable,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ban_status")]
pub enum BanStatus {
    #[sea_orm(string_value = "Active")]
    Active,
    #[sea_orm(string_value = "Expired")]
    Expired,
    #[sea_orm(string_value = "Disabled")]
    Disabled,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "command_active")]
pub enum CommandActive {
    #[sea_orm(string_value = "Active")]
    Active,
    #[sea_orm(string_value = "Disabled")]
    Disabled,
    #[sea_orm(string_value = "Invisible")]
    Invisible,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "command_access")]
pub enum CommandAccess {
    #[sea_orm(string_value = "Any")]
    Any,
    #[sea_orm(string_value = "AnyHidden")]
    AnyHidden,
    #[sea_orm(string_value = "AnyVisible")]
    AnyVisible,
    #[sea_orm(string_value = "GlobalVisible")]
    GlobalVisible,
    #[sea_orm(string_value = "TeamVisible")]
    TeamVisible,
    #[sea_orm(string_value = "SquadVisible")]
    SquadVisible,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "adkats_read")]
pub enum AdkatsRead {
    #[sea_orm(string_value = "Y")]
    Y,
    #[sea_orm(string_value = "N")]
    N,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ban_enforceName")]
pub enum BanEnforceName {
    #[sea_orm(string_value = "Y")]
    Y,
    #[sea_orm(string_value = "N")]
    N,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ban_enforceGUID")]
pub enum BanEnforceGuid {
    #[sea_orm(string_value = "Y")]
    Y,
    #[sea_orm(string_value = "N")]
    N,
}
