//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tbl_games")]
pub struct Model {
    #[sea_orm(column_name = "GameID", primary_key)]
    pub game_id: u8,
    #[sea_orm(column_name = "Name", unique)]
    pub name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::adkats_specialplayers::Entity")]
    AdkatsSpecialplayers,
}

impl Related<super::adkats_specialplayers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdkatsSpecialplayers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
