//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tbl_dogtags")]
pub struct Model {
    #[sea_orm(column_name = "KillerID", primary_key, auto_increment = false)]
    pub killer_id: u32,
    #[sea_orm(column_name = "VictimID", primary_key, auto_increment = false)]
    pub victim_id: u32,
    #[sea_orm(column_name = "Count")]
    pub count: u16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_server_player::Entity",
        from = "Column::KillerId",
        to = "super::tbl_server_player::Column::StatsId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblServerPlayer2,
    #[sea_orm(
        belongs_to = "super::tbl_server_player::Entity",
        from = "Column::VictimId",
        to = "super::tbl_server_player::Column::StatsId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblServerPlayer1,
}

impl ActiveModelBehavior for ActiveModel {}
