//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tbl_sessions")]
pub struct Model {
    #[sea_orm(column_name = "SessionID", primary_key)]
    pub session_id: u32,
    #[sea_orm(column_name = "StatsID")]
    pub stats_id: u32,
    #[sea_orm(column_name = "StartTime")]
    pub start_time: DateTime,
    #[sea_orm(column_name = "EndTime")]
    pub end_time: DateTime,
    #[sea_orm(
        column_name = "Score",
        column_type = "Custom(\"MEDIUMINT(9)\".to_owned())"
    )]
    pub score: String,
    #[sea_orm(column_name = "Kills")]
    pub kills: u16,
    #[sea_orm(column_name = "Headshots")]
    pub headshots: u16,
    #[sea_orm(column_name = "Deaths")]
    pub deaths: u16,
    #[sea_orm(column_name = "TKs")]
    pub t_ks: u16,
    #[sea_orm(column_name = "Suicide")]
    pub suicide: u16,
    #[sea_orm(column_name = "RoundCount")]
    pub round_count: u8,
    #[sea_orm(
        column_name = "Playtime",
        column_type = "Custom(\"MEDIUMINT(8) UNSIGNED\".to_owned())"
    )]
    pub playtime: String,
    #[sea_orm(column_name = "Killstreak")]
    pub killstreak: u16,
    #[sea_orm(column_name = "Deathstreak")]
    pub deathstreak: u16,
    #[sea_orm(
        column_name = "HighScore",
        column_type = "Custom(\"MEDIUMINT(8) UNSIGNED\".to_owned())"
    )]
    pub high_score: String,
    #[sea_orm(column_name = "Wins")]
    pub wins: u8,
    #[sea_orm(column_name = "Losses")]
    pub losses: u8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_server_player::Entity",
        from = "Column::StatsId",
        to = "super::tbl_server_player::Column::StatsId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblServerPlayer,
}

impl Related<super::tbl_server_player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblServerPlayer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
