//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tbl_currentplayers")]
pub struct Model {
    #[sea_orm(column_name = "ServerID", primary_key, auto_increment = false)]
    pub server_id: i16,
    #[sea_orm(column_name = "Soldiername", primary_key, auto_increment = false)]
    pub soldiername: String,
    #[sea_orm(column_name = "GlobalRank")]
    pub global_rank: u16,
    #[sea_orm(column_name = "ClanTag")]
    pub clan_tag: Option<String>,
    #[sea_orm(column_name = "Score")]
    pub score: i32,
    #[sea_orm(column_name = "Kills")]
    pub kills: i32,
    #[sea_orm(column_name = "Headshots")]
    pub headshots: i32,
    #[sea_orm(column_name = "Deaths")]
    pub deaths: i32,
    #[sea_orm(column_name = "Suicide")]
    pub suicide: Option<i32>,
    #[sea_orm(column_name = "Killstreak")]
    pub killstreak: Option<i16>,
    #[sea_orm(column_name = "Deathstreak")]
    pub deathstreak: Option<i16>,
    #[sea_orm(column_name = "TeamID")]
    pub team_id: Option<i8>,
    #[sea_orm(column_name = "SquadID")]
    pub squad_id: Option<i8>,
    #[sea_orm(column_name = "EA_GUID")]
    pub ea_guid: String,
    #[sea_orm(column_name = "PB_GUID")]
    pub pb_guid: String,
    #[sea_orm(column_name = "IP_aton")]
    pub ip_aton: Option<u32>,
    #[sea_orm(column_name = "CountryCode")]
    pub country_code: Option<String>,
    #[sea_orm(column_name = "Ping")]
    pub ping: Option<i16>,
    #[sea_orm(column_name = "PlayerJoined")]
    pub player_joined: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
