//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tbl_weapons_stats")]
pub struct Model {
    #[sea_orm(column_name = "StatsID", primary_key, auto_increment = false)]
    pub stats_id: u32,
    #[sea_orm(column_name = "WeaponID", primary_key, auto_increment = false)]
    pub weapon_id: u32,
    #[sea_orm(column_name = "Kills")]
    pub kills: u32,
    #[sea_orm(column_name = "Headshots")]
    pub headshots: u32,
    #[sea_orm(column_name = "Deaths")]
    pub deaths: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_server_player::Entity",
        from = "Column::StatsId",
        to = "super::tbl_server_player::Column::StatsId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblServerPlayer,
}

impl Related<super::tbl_server_player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblServerPlayer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
