//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tbl_extendedroundstats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub roundstat_id: u32,
    pub server_id: u16,
    pub round_id: u32,
    #[sea_orm(column_name = "round_elapsedTimeSec")]
    pub round_elapsed_time_sec: u32,
    pub team1_count: u32,
    pub team2_count: u32,
    pub team1_score: i32,
    pub team2_score: i32,
    pub team1_spm: f64,
    pub team2_spm: f64,
    pub team1_tickets: i32,
    pub team2_tickets: i32,
    pub team1_tpm: f64,
    pub team2_tpm: f64,
    pub roundstat_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
