name: docker-ci

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  RELEASE_VERSION: ${{ github.run_number }}
  GIT_VERSION_HASH: ${{ github.sha }}

jobs:
  battlefox_web:
    name: Build battlefox_web docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set commit tag to env
        run: echo "COMMIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Print release version
        run: |
          echo $COMMIT_TAG
          echo ${{ env.COMMIT_TAG }}

      # Creating builder (fancier docker build)
      - uses: docker/setup-buildx-action@v1
        id: builder_battlefox_web
      - name: Battlefox builder name
        run: echo ${{ steps.builder_battlefox_web.outputs.name }}
      # Caching layers for faster building
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Logging in to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Building image and pushing it to DockerHub
      - name: Build battlefox_web and push
        id: battlefox_web_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder_battlefox_web.outputs.name }}
          context: .
          file: ./battlefox_web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/battlefox_web:${{ env.COMMIT_TAG }},${{ secrets.DOCKER_USERNAME }}/battlefox_web:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # Printing image digests
      - name: Image digest for battlefox
        run: echo ${{ steps.battlefox_web_build.outputs.digest }}

  battlefox:
    name: Build battlefox docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set commit tag to env
        run: echo "COMMIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Print release version
        run: |
          echo $COMMIT_TAG
          echo ${{ env.COMMIT_TAG }}

      # Creating builder (fancier docker build)
      - uses: docker/setup-buildx-action@v1
        id: builder_battlefox
      - name: Battlefox builder name
        run: echo ${{ steps.builder_battlefox.outputs.name }}
      # Caching layers for faster building
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Logging in to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Building image and pushing it to DockerHub
      - name: Build battlefox and push
        id: battlefox_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder_battlefox.outputs.name }}
          context: .
          file: ./battle_fox/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/battlefox:${{ env.COMMIT_TAG }},${{ secrets.DOCKER_USERNAME }}/battlefox:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # Printing image digests
      - name: Image digest for battlefox
        run: echo ${{ steps.battlefox_build.outputs.digest }}

  battlefox_discord:
    name: Build battlefox_discord docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set commit tag to env
        run: echo "COMMIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Print release version
        run: |
          echo $COMMIT_TAG
          echo ${{ env.COMMIT_TAG }}

      # Creating builder
      - uses: docker/setup-buildx-action@v1
        id: builder_battlefox_discord
      # Printing builder
      - name: battlefox_discord builder name
        run: echo ${{ steps.builder_battlefox_discord.outputs.name }}
      # Caching layers for faster building
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Logging in to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Building image and pushing it to DockerHub
      - name: Build battlefox_discord and push
        id: battlefox_discord_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder_battlefox.outputs.name }}
          context: .
          file: ./discord_integration/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/battlefox_discord:${{ env.COMMIT_TAG }},${{ secrets.DOCKER_USERNAME }}/battlefox_discord:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # Printing image digests
      - name: Image digest for battlefox_discord
        run: echo ${{ steps.battlefox_discord_build.outputs.digest }}